apiVersion: apps/v1
kind: Deployment
metadata:
  name: tti301-consulta-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tti301-consulta
  template:
    metadata:
      labels:
        app: tti301-consulta
    spec:
      containers:
        - name: tti301-consulta
          image: lcstuber/tti301-consulta
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: tti301-consulta-clusterip-service
spec:
  selector:
    app: tti301-consulta
  type: ClusterIP
  ports:
    - name: tti301-consulta
      protocol: TCP
      port: 6000
      targetPort: 6000
