apiVersion: apps/v1
kind: Deployment
metadata:
  name: tti301-logs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tti301-logs
  template:
    metadata:
      labels:
        app: tti301-logs
    spec:
      containers:
        - name: tti301-logs
          image: lcstuber/tti301-logs
          ports:
            - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: tti301-logs-clusterip-service
spec:
  selector:
    app: tti301-logs
  type: ClusterIP
  ports:
    - name: tti301-logs
      protocol: TCP
      port: 2000
      targetPort: 2000