apiVersion: apps/v1
kind: Deployment
metadata:
  name: tti301-observacoes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tti301-observacoes
  template:
    metadata:
      labels:
        app: tti301-observacoes
    spec:
      containers:
        - name: tti301-observacoes
          image: lcstuber/tti301-observacoes
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: tti301-observacoes-clusterip-service
spec:
  selector:
    app: tti301-observacoes
  type: ClusterIP
  ports:
    - name: tti301-observacoes
      protocol: TCP
      port: 5000
      targetPort: 5000